//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ControlHoraEntities : DbContext
    {
        public ControlHoraEntities()
            : base("name=ControlHoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<IngresoHora> IngresoHora { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MesProceso> MesProceso { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<PerfilPrivilegio> PerfilPrivilegio { get; set; }
        public virtual DbSet<Privilegio> Privilegio { get; set; }
        public virtual DbSet<ProyectoEmpleado> ProyectoEmpleado { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
    
        public virtual ObjectResult<Get_EmpleadosConHoras_Result> Get_EmpleadosConHoras()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_EmpleadosConHoras_Result>("Get_EmpleadosConHoras");
        }
    }
}
