//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoHora
    {
        public int IdIngresoHora { get; set; }
        public int IdProyectoEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Hora { get; set; }
        public bool Vigente { get; set; }
    
        public virtual ProyectoEmpleado ProyectoEmpleado { get; set; }
    }
}
