//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilPrivilegio
    {
        public int IdPerfilPrivilegio { get; set; }
        public int IdPerfil { get; set; }
        public int IdPrivilegio { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Privilegio Privilegio { get; set; }
    }
}
